/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MyDictionaryGUI;

import javax.swing.JOptionPane;


/**
 *
 * @author lehuutri
 */
public class AddWordDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddWordDialog
     */
    public AddWordDialog(java.awt.Frame parent, boolean modal, boolean isEng) {
        super(parent, modal);
        initComponents();
        
        newWord.setText("Từ Mới");
        wordLabel.setText("Từ:");
        meaningLabel.setText("Ý nghĩa:");
        AddNewWord.setText("Thêm từ");
        Cancel.setText("Huỷ");
        if (isEng) {
            newWord.setText("New Word");
            wordLabel.setText("Word:");
            meaningLabel.setText("Meaning:");
            AddNewWord.setText("Add");
            Cancel.setText("Cancel");
        }
        
        AddNewWord.addActionListener(e -> {
            if (wordTf.getText().strip().equals("")) {
                if (isEng)
                    JOptionPane.showMessageDialog(this, "Please input a word");
                else
                    JOptionPane.showMessageDialog(this, "Hãy nhập một từ");

                    
                return;
            }

            if (meaningTf.getText().strip().equals("")) {
                if (isEng)
                    JOptionPane.showMessageDialog(this, "Please input the meaning");
                else
                    JOptionPane.showMessageDialog(this, "Hãy thêm ý nghĩa của từ");


                return;
            }

            dispose();

            createNewWord = true;
        });
        
        Cancel.addActionListener(e -> {
            dispose();
            createNewWord = false;
        });
    }
    
    boolean createNewWord = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        wordTf = new javax.swing.JTextField();
        wordLabel = new javax.swing.JLabel();
        meaningLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        meaningTf = new javax.swing.JTextArea();
        newWord = new javax.swing.JLabel();
        AddNewWord = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MyDictionary");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(166, 209, 255));

        jPanel2.setBackground(new java.awt.Color(89, 50, 213));
        jPanel2.setForeground(new java.awt.Color(89, 50, 213));

        wordTf.setFont(new java.awt.Font("SVN-Aguda", 0, 13)); // NOI18N

        wordLabel.setFont(new java.awt.Font("SVN-Aguda", 0, 14)); // NOI18N
        wordLabel.setForeground(new java.awt.Color(255, 255, 255));
        wordLabel.setText("Word:");

        meaningLabel.setFont(new java.awt.Font("SVN-Aguda", 0, 14)); // NOI18N
        meaningLabel.setForeground(new java.awt.Color(255, 255, 255));
        meaningLabel.setText("Meaning:");

        meaningTf.setColumns(20);
        meaningTf.setFont(new java.awt.Font("SVN-Aguda", 0, 13)); // NOI18N
        meaningTf.setLineWrap(true);
        meaningTf.setRows(5);
        jScrollPane1.setViewportView(meaningTf);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(meaningLabel)
                    .addComponent(wordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(wordTf))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meaningLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        newWord.setFont(new java.awt.Font("SVN-Kimberley", 0, 24)); // NOI18N
        newWord.setForeground(new java.awt.Color(89, 50, 213));
        newWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newWord.setText("New Word");

        AddNewWord.setBackground(new java.awt.Color(89, 50, 213));
        AddNewWord.setFont(new java.awt.Font("SVN-Aguda", 0, 18)); // NOI18N
        AddNewWord.setForeground(new java.awt.Color(255, 255, 255));
        AddNewWord.setText("Add");

        Cancel.setBackground(new java.awt.Color(50, 50, 50));
        Cancel.setFont(new java.awt.Font("SVN-Aguda", 0, 18)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 255));
        Cancel.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newWord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AddNewWord, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cancel))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(newWord)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewWord)
                    .addComponent(Cancel))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public String[] showDialog() {
        this.setVisible(true);
       
        
        if (createNewWord)
        {
            return new String[]{wordTf.getText().strip(), meaningTf.getText().strip()};
        }
        
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewWord;
    private javax.swing.JButton Cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel meaningLabel;
    private javax.swing.JTextArea meaningTf;
    private javax.swing.JLabel newWord;
    private javax.swing.JLabel wordLabel;
    private javax.swing.JTextField wordTf;
    // End of variables declaration//GEN-END:variables
}
